- hosts: web
  remote_user: root
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Install Apache
    ansible.builtin.dnf:
      name: httpd
      state: installed
  - name: Restart Apache
    service:
      name: httpd
      state: restarted
  - name: Remove Apache
    ansible.builtin.dnf:
      name: httpd
      state: removed